[package]
name = "session-tree-toy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abomonation = "0.7"
chrono = "0.4"
differential-dataflow = "0.11.0"
timely = "0.11.1"
